/**
 * Testtreiber ePA-Frontend des Versicherten
 * REST Schnittstelle einer Test-App fuer das ePA-Modul FdV
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.fluentcodes.ihe.gematik.fdv.api;

import org.fluentcodes.ihe.gematik.fdv.model.ChangeProviderRequestDTO;
import org.fluentcodes.ihe.gematik.fdv.model.NotificationInformationRequestDTO;
import org.fluentcodes.ihe.gematik.fdv.model.ResponseDTO;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Testtreiber ePA-Frontend des Versicherten
 *
 * <p>REST Schnittstelle einer Test-App fuer das ePA-Modul FdV
 *
 * API tests for AdministrationApi 
 */
public class AdministrationApiTest {


    private AdministrationApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://gematik.de/fdv", AdministrationApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Anbieter wechseln
     *
     * Umsetzung Operation I_FdV::changeProvicer (A_18047)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changeProvider1Test() {
        ChangeProviderRequestDTO changeProviderRequestDTO = null;
        //ResponseDTO response = api.changeProvider1(changeProviderRequestDTO);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Benachrichtigungsadresse fuer Geraeteautorisierung aktualisieren
     *
     * Umsetzung Operation I_FdV::putNotificationInformation (A_18063); Hinterlegt eine Benachrichtigungsadresse fuer das Aktenkonto.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putNotificationInformation1Test() {
        NotificationInformationRequestDTO notificationInformationRequestDTO = null;
        //ResponseDTO response = api.putNotificationInformation1(notificationInformationRequestDTO);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
}
