/**
 * Testtreiber ePA-Frontend des Versicherten
 * REST Schnittstelle einer Test-App fuer das ePA-Modul FdV
 *
 * The version of the OpenAPI document: 2.0.4
 * Contact: software-development@gematik.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fluentcodes.ihe.gematik.fdv.api;

import org.fluentcodes.ihe.gematik.fdv.model.ProtocolResponseDTO;
import org.fluentcodes.ihe.gematik.fdv.model.RequestDTO;
import org.fluentcodes.ihe.gematik.fdv.model.SignedProtocolResponseDTO;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Testtreiber ePA-Frontend des Versicherten
 *
 * <p>REST Schnittstelle einer Test-App fuer das ePA-Modul FdV
 *
 * API tests for ProtocolApi
 */
public class ProtocolApiTest {


    private ProtocolApi api;

    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);

        api = JAXRSClientFactory.create("https://frontend.titus.ti-dienste.de", ProtocolApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);

        ClientConfiguration config = WebClient.getConfig(client);
    }

    
    /**
     * Zugriffsprotokolle lesen
     *
     * Diese Operation führt den Anwendungsfall \&quot;Zugriffsprotokoll einsehen\&quot; in einer mit insurantId identifizierten Aktensession aus. Die vom Aktensystem gelieferten Protokolleinträge werden aufgearbeitet und zurückgegeben. Liefert alle Einträge aus dem §291a und Verwaltungsprotokoll für das Aktenkonto.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProtocol1Test() {
        RequestDTO requestDTO = null;
        //ProtocolResponseDTO response = api.getProtocol1(requestDTO);
        //assertNotNull(response);
        // TODO: test validations


    }
    
    /**
     * Zugriffsprotokolle mit PAdES-Signatur lesen
     *
     * Diese Operation führt den Anwendungsfall \&quot;signiertes Zugriffsprotokoll einsehen\&quot; in einer mit insurantId identifizierten Aktensession aus. Die vom Aktensystem gelieferten Protokolleinträge werden aufgearbeitet und zurückgegeben. Liefert alle Einträge aus getSignedAuditEvents für das Aktenkonto.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSignedProtocol1Test() {
        RequestDTO requestDTO = null;
        //SignedProtocolResponseDTO response = api.getSignedProtocol1(requestDTO);
        //assertNotNull(response);
        // TODO: test validations


    }
    
}
